### ISSUE TITLE
시놀로지 도커로 여기 설명대로 설치했는데 한글프로젝트명이 안되요

### ISSUE THREAD

**Issue by syseop** [pokev25/docker-yona#10]
한글 프로젝트명을 사용하면 에러가 나요
설치 가이드(https://repo.yona.io/yona-projects/yona/issue/26
시놀로지 도커에 yona설치하기)를 따라 그대로 했구요.
yona는 최신번전을 썼어요

[error] play - Cannot invoke the action, eventually got an error: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /root/yona_data/repo/git/admin/???.git/config
[error] application -

에러 내용은 이렇구요. CentOS버전까지 아래 안내서에 나온 대로 설정을 했는데 동일한 증상입니다.
https://repo.yona.io/yona-projects/yona/issue/26

 이쪽에도 남겨보라해서 옮겨 썼습니다만....

**Comment by pokev25** [comment]
저쪽에 답글 남겼습니다.
locale 때문인것으로 보입니다.

이미지를 받고 컨테이너 생성해서 한글 폴더 생성해보면 ls 해서 ??? 로 나옵니다.

```sh
docker pull centos:7.4.1708
docker run --rm -it centos:centos7 bash
```
제가 사용하는 이미지로 테스트 해보니 한글 폴더명이 잘 보입니다.
```sh
docker pull openjdk:8-jdk-alpine3.9
docker run --rm -it openjdk:8-jdk-alpine3.9 sh
```

**Comment by pokev25** [comment]
설명보신 문서대로 하시는것보다는 제가 올린 이미지 받으시고

db와 네트워크 설정만 설명문대로 하시고 연결 시켜보세요.
