### ISSUE TITLE
도커로 두개 이상의 Yona를 돌리고싶은데, DB를 따로 쓸 순 없을까요?

### ISSUE THREAD

**Issue by dinobei** [pokev25/docker-yona#2]
Yona를 두개 실행해서 하나는 로컬에서만 접속되도록, 하나는 외부 접속이 가능하도록 하려고합니다.

현재는 Host의 MariaDB에 Connect해서 서비스를 시작하는거같은데, 컨테이너에서 DB를 유지하도록 변경하는건 어떨까요?

**Comment by pokev25** [comment]
컨테이너 내부에 DB를 두지 않은건 일부러 그렇게 한겁니다.

필요하신대로 수정해서 사용하시면 될 것 같습니다.

**Comment by pokev25** [comment]
도커 별도의 디렉토리 지정해서 두개띄우고 포트와 DB 접속 정보를 각각 주면 두개 동작 할껍니다.
