### ISSUE TITLE
[문의] Docker를 이용해 yona를 설치하였습니다.

### ISSUE THREAD

**Issue by limdh7231** [pokev25/docker-yona#3]
./shell/yona.sh build 이후 

./shell/yona.sh init 한 이후에 ./shell/yona.sh log를 확인해보면 

[error] c.j.b.h.AbstractConnectionHook - Failed to obtain initial connection Sleeping for 0ms and trying again. Attempts left: 0. Exception: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect to address=(host=127.0.0.1)(port=3306)(type=master) : Connection refused (Connection refused).Message:Could not connect to address=(host=127.0.0.1)(port=3306)(type=master) : Connection refused (Connection refused)
Configuration error: Configuration error[Cannot connect to database [default]]
        at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94)
        at play.api.Configuration.reportError(Configuration.scala:743)
...

와 같은 로그가 발생합니다. docker를 통한 설치 시 MariaDB 까지 자동 설치되는 것인지가요?

아니면 MariaDB의 경우 별도로 설치를 해야 하는건가요? 별도로 설치를 해야 할 경우 DB 접속 정보는 어디에서 수정을 해야할지 잘 모르겠습니다.

**Comment by pokev25** [comment]
DB는 별도 설치 를 해야 합니다.

설정을 안바꾸셨다면 실행 경로에 data 디렉토리가 있고 그안에 conf/application.conf
애서 수정 하시면 됩니다.

**Comment by limdh7231** [comment]
아~ 답변감사합니다.
