### ISSUE TITLE
docker-compose 재구성

### ISSUE THREAD

**Issue by nayasis** [pokev25/docker-yona#7]
안녕하세요.

작업중이신 내용과 상이한 부분이 많아, fork 떠서 요청드리지 못하고 이렇게 issues에 글타래 남기네요.

mariadb, yona 를 각각 container로 만들어 구동하는 방법으로 docker-compose.yml을 구성해 보았습니다.

[yona_script.zip](https://github.com/pokev25/docker-yona/files/2606769/yona_script.zip)

docker 배포환경 구성시 참조가 될 수 있을 것 같아, 내용 공유드립니다.

감사합니다.

**Comment by pokev25** [comment]
감사 합니다 참고 하겠습니다.

**Comment by pokev25** [comment]
아 미리 mariadb에 yona db를 생성한 이미지를 연결 하는 방식이군요.
