### ISSUE TITLE
ARG 바인딩 문제

### ISSUE THREAD

**Issue by nGusto** [pokev25/docker-yona#8]
Dockerfile 내의 5-7번 라인이 특정 상황에서 비정상 작동하는 문제가 있습니다.

테스트 환경은 Synology Nas 918+ 입니다.

```
ARG YONA_VERSION=1.11.1
ARG YONA_BIN=yona-v${YONA_VERSION}-bin.zip
ARG YONA_DOWNLOAD_URL=https://github.com/yona-projects/yona/releases/download/v${YONA_VERSION}/${YONA_BIN}
```

ARG 에 값이 제대로 바인딩 되지 않아 하단 wget 과 rename 부분 등에서 오류가 발생합니다.

빌드 시 build-arg YONA_VERSION=1.11.1 값을 넘겨주는 등의 여러가지 방법으로 해보았지만 값이 바인딩 되지 않아서 임시 방편으로 ARG 를 ENV 로 변경하여 해결하였습니다.

시간 여유 되시면 확인 부탁드립니다.

**Comment by pokev25** [comment]
아 시놀로지는 뭔가 다른 모양이군요. ENV로 바꿔봐야겠습니다.

**Comment by pokev25** [comment]
그런데 시놀로지에서 빌드해서 사용하시는 이유가 있으신가요? 
docker pull pokev25/yona:1.11.1
로 받아서 쓰셔도 될텐데요.

**Comment by nGusto** [comment]
> 그런데 시놀로지에서 빌드해서 사용하시는 이유가 있으신가요?
> docker pull pokev25/yona:1.11.1
> 로 받아서 쓰셔도 될텐데요.

특별한 목적이 있는 것은 아니고 시놀로지에서 yona를 올려서 사용하려는 목적으로 테스트하고 있습니다. 위 오류 리포트 드린 것은 좀 더 편하게 사용하기 위해서 docker-compose 로 빌드해서 db 연동까지 하는 과정에서 발생했던 오류고요.

docker-compose.yml 세팅 후에 빌드하면 db 연동(그 외디비 연동)이나 NT나 리눅스에서 문제가 없이 작동하는지 등에 대한 테스트하는 단계에서 NT서버에서는 db 권한 문제가 발생했고, 시놀로지에서 바인딩 문제가 발생해서 그에 대한 리포트를 드리게 되었습니다.
